### ISSUE TITLE
Failure on installation due to firefox dependency issue

### ISSUE THREAD

**Issue by johnsaigle** [kousu/arch-conf#1]
Hi!

I got this error message when running `sudo pacman -U kousu-device-nigiri-....`. (Also I'm typing out this error message because I can't yet copy-paste from the arch system.)

```
warning: cannot resolve "firefox-clearurls", a dependency of "kousu-device-nigiri"
warning: cannot resolve "firefox-extension-privacybadger", a dependency of "kousu-device-nigiri"
:: The following package cannot be upgraded due to unresolvable dependencies:
    kousu-device-nigiri
```

**Comment by kousu** [comment]
@johnsaigle give it a shot again, it should work now?

**Comment by johnsaigle** [comment]
Yeah I ended up deleting those lines and it proceeded after that! Still having some issues getting the rest of the system running but that's most likely due to my Arch-newbness rather than this code.

If there are other bugs I'll open other issues
